### ISSUE TITLE
Add variable 'jumps' using set

### ISSUE THREAD

**Issue by Kyllingene** [neumond/minpiler#10]
In mlog, you can use ```set @counter <number>``` to jump to ```<number>```, making a bunch of stuff possible, like functions (probably hard to implement, but doable) and jumping to variable positions.

**Comment by neumond** [comment]
Function support has been planned in #7 and #8. Although it's easy to add some builtin like

```py
Processor.counter = 6
```

I doubt it will be very useful. Could you provide some example of its use case (in python)?

**Comment by Kyllingene** [comment]
Oh, I'm sorry, I phrased it weirdly. What I meant is you could utilize ```set @counter <number>``` to make functions in minpiler. Sorry, I probably just misunderstood #7 and #8. Idk why I assumed you didn't know about ```@counter```.

**Comment by neumond** [comment]
Yea, thank you for help, `@counter` was really undocumented and hard to discover thing I've learned about in Discord channels. Before I knew about it, I imagined finding return point via decision tree, but `@counter` makes it much easier.
