### ISSUE TITLE
Autocomplete Stubs

### ISSUE THREAD

**Issue by riandrake** [neumond/minpiler#13]
Any possibility we could get autocomplete stubs made/generated for writing scripts? Would help a lot with writing scripts faster, especially for people new to Mindustry scripting like myself! Something like this would be sufficient:

```
# M/draw.py

def clear(r, g, b):
    pass

def color(r, g, b, a):
    pass
```

**Comment by neumond** [comment]
There's `typeshed` module for this, but it's quite outdated.
